#if !canImport(ObjectiveC)
import XCTest

extension NameStyling_Spec {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NameStyling_Spec = [
        ("test_Printing_transforms_camel_case_to_kebab_case", test_Printing_transforms_camel_case_to_kebab_case),
        ("test_Reading_transforms_kebab_case_to_camel_case", test_Reading_transforms_kebab_case_to_camel_case),
    ]
}

extension Print_Spec {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Print_Spec = [
        ("test_Printing_lists", test_Printing_lists),
        ("test_Printing_literals_screens_quotes", test_Printing_literals_screens_quotes),
        ("test_Printing_many_items_is_reasonably_fast", test_Printing_many_items_is_reasonably_fast),
        ("test_Printing_nested_struct", test_Printing_nested_struct),
        ("test_Printing_simple_struct", test_Printing_simple_struct),
        ("test_Printing_trivial_structure", test_Printing_trivial_structure),
    ]
}

extension Read_Spec {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Read_Spec = [
        ("test_Reading_anything_except_struct__list_or_atom_throws", test_Reading_anything_except_struct__list_or_atom_throws),
        ("test_Reading_from_empty_string_throws", test_Reading_from_empty_string_throws),
        ("test_Reading_list_creates_an_array_of_entities", test_Reading_list_creates_an_array_of_entities),
        ("test_Reading_many_items_is_reasonably_fast", test_Reading_many_items_is_reasonably_fast),
        ("test_Reading_nested_structure", test_Reading_nested_structure),
        ("test_Reading_simple_structure_ignores_additional_spaces_and_newlines", test_Reading_simple_structure_ignores_additional_spaces_and_newlines),
        ("test_Reading_simple_structure_styled_in_CL", test_Reading_simple_structure_styled_in_CL),
        ("test_Reading_simple_structure_with_duplicate_keys_throws", test_Reading_simple_structure_with_duplicate_keys_throws),
        ("test_Reading_simple_structure_with_malformed_number_throws", test_Reading_simple_structure_with_malformed_number_throws),
        ("test_Reading_simple_structure_with_unclear_field_names_throws", test_Reading_simple_structure_with_unclear_field_names_throws),
        ("test_Reading_simple_structure", test_Reading_simple_structure),
        ("test_Reading_structure_with_screened_quotes_unscreens_them_in_value", test_Reading_structure_with_screened_quotes_unscreens_them_in_value),
        ("test_Reading_trivial_structure", test_Reading_trivial_structure),
        ("test_Reading_unnamed_struct_throws", test_Reading_unnamed_struct_throws),
    ]
}

extension Tokenizer_Spec {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Tokenizer_Spec = [
        ("test_Literal_tokenization_unscreens_slashes_and_quotes", test_Literal_tokenization_unscreens_slashes_and_quotes),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(NameStyling_Spec.__allTests__NameStyling_Spec),
        testCase(Print_Spec.__allTests__Print_Spec),
        testCase(Read_Spec.__allTests__Read_Spec),
        testCase(Tokenizer_Spec.__allTests__Tokenizer_Spec),
    ]
}
#endif
